name: hello-world
on: push
jobs:
  helloworld-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.4.0
    
      - name: print message
        run: echo "Hello World from GitHub Actions!"
        
      - name: run multiline script
        run: |
          echo First line,
          echo Second line

      - name: show current directory content
        run: |
          ls
      
      - name: show parent directory content
        run: |
          cd ..
          ls
