name: CI on Xamarin Android Project
on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.4.0
        
      - name: Android
        run: |
          nuget restore
          cd AwesomeXamarinApp
          cd AwesomeXamarinApp.Android
          msbuild AwesomeXamarinApp.Android.csproj /verbosity:normal /t:Rebuild /t:PackageForAndroid /t:SignAndroidPackage /p:Configuration=Debug
          
      - name: Obtain Android APK file
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Xamarin Awesome App
          path: AwesomeXamarinApp/AwesomeXamarinApp.Android/bin/Debug/com.companyname.awesomexamarinapp-Signed.apk
