name: CI on Xamarin Android Project
on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.4.0
        
      - name: Android
        run: |
          nuget restore
          cd AwesomeXamarinApp
          cd AwesomeXamarinApp.Android
          msbuild AwesomeXamarinApp.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
